### ISSUE TITLE
Build failure?

### ISSUE THREAD

**Issue by cerkyp** [HL7/genomics-unified#2]
@liulei6696 - It seems your latest commit generated a build failure?

http://build.fhir.org/ig/HL7/genomics-unified/build.log

**Comment by liulei6696** [comment]
Fixed

**Comment by cerkyp** [comment]
Confirmed:
IG Build Bot  Bot 11:36 AM   
HL7/genomics-unified rebuilt
Commit: update usecases.xml
(liulei) :thumbs_up:
Details: build logs | published | qa: broken links = 1, errors = 10, warn = 4, info = 9
