### ISSUE TITLE
Question about how to represent the relationship of the arrow sign of the diagram

### ISSUE THREAD

**Issue by xliu3** [HL7/genomics-unified#4]
I am working on the PGx example, and got question about the schema diagram:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/12411995/36993529-1841f426-207c-11e8-8af9-d94a296a773e.png">

From the above picture, There is a arrow sign from Genotype/Haplotype/Variant to the Computable Genetics Finding, also have to same sign from the computable genetic finding to the genetic finding. Wonder how to actual FHIR json will represent this relationship?
@lmckenzi

**Comment by lmckenzi** [comment]
The FHIR JSON doesn't include anything that's in red - those are for diagramming purposes only.  So ComputableGeneticFinding, DescriptiveGeneticFinding will identify as their parent the first non-red ancestor you encounter when traversing the "generalization" arrows in the diagrams - which in this case is GeneticObservation

**Comment by xliu3** [comment]
Another problem is that how to represent the parent relationship between ComputaableGeneticFinding with Genotype/Haplotype/Variant.

**Comment by lmckenzi** [comment]
That relationship already exists through the parent link for the profile

**Comment by cerkyp** [comment]
I think she is asking that when it comes to real instances, what is the relationship?  I think the answer is that there will not be real instances of ComputableGeneticFinding profiles?  Instead, the Genotype/Haplotype/Variant instances would include all of the properties of the  ComputableGeneticFinding profile?

**Comment by cerkyp** [comment]
I wonder if it is worth indicating the abstract profiles in some way on the diagrams?

**Comment by lmckenzi** [comment]
As per UML convention, the class names show up in italics

**Comment by xliu3** [comment]
So it looks like for the real instances, the connection between the Genotype/Haplotype/Variant will be within the DiagnosticsReport.result. From the diagnosticsReport detail section of the IG. I saw it include the ComplexVariant, DescribedVariant, and CytogeneticNotation within the results of the diagnosticReport. Wonder if the Genotype and Haplotype will need to be listed in this section if the example have these items.

**Comment by lmckenzi** [comment]
The connection between Genotype, Haplotype and Variant are explicit as derivedFrom.  Everything is linked to the DiagnosticReport via DiagnosticReport.result

**Comment by xliu3** [comment]
okay. Got it.
