### ISSUE TITLE
Question about the value for the Component(Simple var ID) in the DescribedVariant Profile

### ISSUE THREAD

**Issue by xliu3** [HL7/genomics-unified#5]
Hello All,
When I am making the example, I faced a difficulty to identify what kind of information to store inside valueCodeableConcept of the Component(Simple var id) of  the Described Variant Profile. Wonder what the different between this with the dbSNP id as well.

**Comment by cerkyp** [comment]
We talked about this on the call Tuesday.  For the simple var id, you would include 1 or more codings with identifiers from CLINVAR, COSMIC, or other code system/variant database.  We discussed having dbSNP id delivered here, but the feeling from the group was that dbSNP is really only a reference to the location, not the change - so many in the group were uncomfortable considering the dbSNP as a 'variation id'.

Does that make sense?

**Comment by lmckenzi** [comment]
We haven't landed on what the URIs for the respective code systems should
be.  We should probably get HL7 to issue SID URIs that we can use for
them.  If you're willing, can you check what the convention has been for
other code systems identified with SIDs and submit change requests to get
official URLs for all the different external code systems we need.

**Comment by cerkyp** [comment]
There are several code systems for genetics listed here, is that what you are looking for?

http://build.fhir.org/terminologies-systems.html

**Comment by lmckenzi** [comment]
Some, but I think we need more.  (And some of these I think got registered
in error - I'm pretty sure clinicaltrials.gov is not a single code
system...)

**Comment by cerkyp** [comment]
OK.

Regarding ct.gov, perhaps I am not sure what you mean.  But, if you take NCT01238250 assigned by them, you can get to this:

https://www.clinicaltrials.gov/ct2/show/NCT01238250

**Comment by lmckenzi** [comment]
Yeah, that's not a code.  That's an identifier - specifically a
ResearchStudy.identifier.

They absolutely do have codes for things like study type, observational
model, etc. but I'm pretty sure those are maintained as independent code
systems, not as a single monolithic code system like LOINC or SNOMED.

**Comment by cerkyp** [comment]
oh, duh.  I get it, thanks.

**Comment by cerkyp** [comment]
BTW - We can probably close this issue.  I am starting to chase down how to get code and identifier systems setup.
